const provinceList = [
	{ value: "aceh", label: "Aceh" },
	{ value: "sumatera-utara", label: "Sumatera Utara" },
	{ value: "sumatera-barat", label: "Sumatera Barat" },
	{ value: "riau", label: "Riau" },
	{ value: "kepulauan-riau", label: "Kepulauan Riau" },
	{ value: "jambi", label: "Jambi" },
	{ value: "sumatera-selatan", label: "Sumatera Selatan" },
	{ value: "bangka-belitung", label: "Bangka Belitung" },
	{ value: "bengkulu", label: "Bengkulu" },
	{ value: "lampung", label: "Lampung" },
	{ value: "kepulauan-bangka-belitung", label: "Kepulauan Bangka Belitung" },
	{ value: "jakarta", label: "DKI Jakarta" },
	{ value: "jawa-barat", label: "Jawa Barat" },
	{ value: "banten", label: "Banten" },
	{ value: "jawa-tengah", label: "Jawa Tengah" },
	{ value: "daerah-istimewa-yogyakarta", label: "Daerah Istimewa Yogyakarta" },
	{ value: "jawa-timur", label: "Jawa Timur" },
	{ value: "bali", label: "Bali" },
	{ value: "nusa-tenggara-barat", label: "Nusa Tenggara Barat" },
	{ value: "nusa-tenggara-timur", label: "Nusa Tenggara Timur" },
	{ value: "kalimantan-barat", label: "Kalimantan Barat" },
	{ value: "kalimantan-tengah", label: "Kalimantan Tengah" },
	{ value: "kalimantan-selatan", label: "Kalimantan Selatan" },
	{ value: "kalimantan-timur", label: "Kalimantan Timur" },
	{ value: "kalimantan-utara", label: "Kalimantan Utara" },
	{ value: "sulawesi-utara", label: "Sulawesi Utara" },
	{ value: "gorontalo", label: "Gorontalo" },
	{ value: "sulawesi-tengah", label: "Sulawesi Tengah" },
	{ value: "sulawesi-barat", label: "Sulawesi Barat" },
	{ value: "sulawesi-selatan", label: "Sulawesi Selatan" },
	{ value: "sulawesi-tenggara", label: "Sulawesi Tenggara" },
	{ value: "maluku", label: "Maluku" },
	{ value: "maluku-utara", label: "Maluku Utara" },
	{ value: "papua-barat", label: "Papua Barat" },
	{ value: "papua", label: "Papua" },
];

export default provinceList;
